image: "python:3.8"

# Java is needed for hydra-core wheel build (can be removed when hydra 1.1 is out)
# libtinfo5 is needed by Pytorch
before_script:
  - python --version
  - pip --version
  - apt-get update && apt-get upgrade -y && apt-get install -y default-jre libtinfo5
  - pip install -r requirements.txt

stages:
  - test

test:
  stage: test
  script:
    - pytest tests -v --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
