stages:
  download-dataset:
    cmd: python -m solarnet.main download sdo-benchmark-zip
    deps:
      - solarnet/main.py
      - config/minio.yaml
    outs:
      - data/sdo-benchmark.placeholder:
          persist: true
          cache: false

  train-baseline:
    cmd: python -m solarnet.main train
    params:
      - config/config.yaml:
          - data
          - model
          - trainer
          - name
          - seed
          - tracking
          - gpus
    deps:
      - solarnet/main.py
      - solarnet/tasks/train.py
      - solarnet/models/baseline.py
      - data/sdo-benchmark.placeholder
    outs:
      - models/baseline/model.ckpt
      - models/baseline/history.png:
          cache: false
      - models/baseline/model_summary.txt:
          cache: false

  test-baseline:
    cmd: python -m solarnet.main test
    params:
      - config/config.yaml:
          - data
          - model
          - trainer
          - seed
          - gpus
    deps:
      - solarnet/main.py
      - solarnet/tasks/test.py
      - solarnet/models/baseline.py
      - data/sdo-benchmark.placeholder
      - models/baseline/model.ckpt
    metrics:
      - models/baseline/metrics.yaml:
          cache: false
    outs:
      - models/baseline/test_samples.png:
          cache: false
      - models/baseline/confusion_matrix.png:
          cache: false

  generate-report:
    vars:
      - report: "models/baseline/report.md"
    # TODO: add model size (x kB)
    # TODO: add diff with naive method
    # TODO: add number of train/test samples
    cmd: >-
      echo # Model report > ${report} &&
      echo ## Training >> ${report} &&
      echo ### Parameters >> ${report} &&
      echo ```>> ${report} &&
      cat config/config.yaml >> ${report} &&
      echo ```>> ${report} &&
      echo ### Model architecture >> ${report} &&
      echo ```>> ${report} &&
      cat models/baseline/model_summary.txt >> ${report} &&
      echo ```>> ${report} &&
      echo ### Loss curve >> ${report} &&
      printf "![Loss curve](history.png 'Loss curve')\n\n" >> ${report} &&
      echo ## Test >> ${report} &&
      echo ### Metrics >> ${report} &&
      dvc metrics show --show-md >> ${report} &&
      echo ### Confusion matrix >> ${report} &&
      printf "![Confusion matrix](confusion_matrix.png 'Confusion matrix')\n\n" >> ${report} &&
      echo ### Test samples >> ${report} &&
      printf "![Test samples](test_samples.png 'Test samples')\n\n" >> ${report}
    deps:
      - models/baseline/history.png
      - models/baseline/model_summary.txt
      - models/baseline/metrics.yaml
      - models/baseline/test_samples.png
      - models/baseline/confusion_matrix.png
    outs:
      - ${report}:
          cache: false
