data:
  name: sdo-benchmark
  validation_size: 0.1
  channel: magnetogram
  size: 256
  targets:
    classes:
    - Quiet: < 1e-6
    - '>=C': '>= 1e-6'
  time_steps: 3
  path: data/sdo-benchmark
model:
  backbone: simple-cnn
  learning_rate: 0.005
  activation: relu6
  pooling: 2
  dropout: 0.2
  n_hidden: 16
  lr_scheduler: true
trainer:
  epochs: 20
  patience: 12
  batch_size: 128
name: Baseline binary classification model, magnetogram, >=C
training_type: train
tune_lr: false
path: models/baseline_binary_sdobenchmark
seed: 42
tracking: true
system:
  gpus: 1
  workers: 20
tags:
- sdo-benchmark
- Class-C
