data:
  validation_size: 0.1
  channel: 211
  size: 256
  targets: regression
    # classes:
      # - Quiet: "< 1e-6"
      # - "C": "< 1e-5"
      # - "M": "< 1e-4"
      # - "X": ">= 1e-4"
  time_steps: [3]

model:
  activation: relu6

trainer:
  epochs: 20
  batch_size: 128
  learning_rate: 5e-3
  patience: 12

name: Baseline regression model
seed: 42
tracking: true
gpus: 1
