data:
  validation_size: 0.1
  channel: '171'
  size: 256
  targets:
    classes:
      - Quiet: "< 1e-6"
      - ">=C": ">= 1e-6"

model:
  activation: relu

trainer:
  epochs: 25
  batch_size: 64
  learning_rate: 5e-3
  patience: 12

name: Baseline binary classification model
seed: 42
tracking: true
gpus: 1
