defaults:
  - data: sdo-benchmark

model:
  activation: relu6

trainer:
  epochs: 20
  batch_size: 128
  learning_rate: 5e-3
  patience: 12

name: Baseline binary classification model
path: models/binary
seed: 42
tracking: true
gpus: 1
