data:
  name: sdo-benchmark
  validation_size: 0.1
  channel: 211
  size: 256
  targets:
    classes:
    - Quiet: < 1e-6
    - '>=C': '>= 1e-6'
  time_steps:
  - 3
  path: data/sdo-benchmark
model:
  activation: relu6
trainer:
  epochs: 20
  batch_size: 128
  learning_rate: 0.005
  patience: 12
name: Baseline binary classification model
path: models/binary
seed: 42
tracking: true
gpus: 1
