data:
  name: sdo-dataset
  channel: 171
  size: 256
  targets:
    classes:
    - Quiet: < 1e-6
    - '>=C': '>= 1e-6'
  path: /data1/data/sdo-dataset
model:
  activation: leakyrelu
trainer:
  epochs: 20
  batch_size: 128
  learning_rate: 0.001
  patience: 12
name: Binary classification model on SDO-Dataset
path: models/binary_sdodataset
seed: 42
tracking: true
gpus: 1
